### ISSUE TITLE
The app does not work with Cowboy 4

### ISSUE THREAD

**Issue by ldynia** [runerune/BroncoUnleashed#4]
Awesome app, thanks!  Can you make this app work with Cowboy 4 bike Firmware v4.13? At the moment, changing speed limit has no effect.

**Comment by Imaginous** [comment]
Which Cowboy 4 do you have normal or ST?

I'm not aware of any firmware versions that would block the removal of the speed limit.

What value did you use for the Field weakening value?

For a C4 I recommend 15 for a C4ST a value of 13.

Press TEST followed by FLASH to make the settings permanent.

**Comment by ldynia** [comment]
I confirm it works when I set field weakening to 15 and speed limit to 30 km/h.

Maybe it didn't work because initially I set only speed limit  without field weakening.

**Comment by Imaginous** [comment]
You have to set a field weakening to go beyond 30km/h.

But I'm glad it works for you.
